In [1]:
#!wget -O "learn_ml_insurance_prediction__ai_challenge-dataset.zip" "https://dockship-job-models.s3.ap-south-1.amazonaws.com/196c328ad298ef1476f56437902688ef?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210121%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210121T052142Z&X-Amz-Expires=1800&X-Amz-Signature=8c05bd81444868c6fff7909eb63edcd87c2cfef3c85e773be143f55f58166833&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22learn_ml_insurance_prediction__ai_challenge-dataset.zip%22"

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
#!unzip learn_ml_insurance_prediction__ai_challenge-dataset.zip

'unzip' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
#!rm learn_ml_insurance_prediction__ai_challenge-dataset.zip

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("TRAIN.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304887 entries, 0 to 304886
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   id                    304887 non-null  int64 
 1   Gender                304887 non-null  object
 2   Age                   304887 non-null  int64 
 3   Driving_License       304887 non-null  int64 
 4   Region_Code           304887 non-null  int64 
 5   Previously_Insured    304887 non-null  int64 
 6   Vehicle_Age           304887 non-null  object
 7   Vehicle_Damage        304887 non-null  object
 8   Annual_Premium        304887 non-null  int64 
 9   Policy_Sales_Channel  304887 non-null  int64 
 10  Vintage               304887 non-null  int64 
 11  Response              304887 non-null  int64 
dtypes: int64(9), object(3)
memory usage: 27.9+ MB


In [4]:
df.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957    Male   50                1           41                   0   
1  239788  Female   48                1           28                   0   
2  348272  Female   34                1           41                   0   
3   73940  Female   43                1           28                   0   
4  292871    Male   29                1           28                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes           35915                   124      240   
1    1-2 Year            Yes           26873                   124      274   
2    1-2 Year            Yes            2630                   156      138   
3    1-2 Year            Yes           46877                   124      223   
4    < 1 Year             No           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [5]:
df.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [6]:
df['Vehicle_Age'].unique()

array(['1-2 Year', '< 1 Year', '> 2 Years'], dtype=object)

In [7]:
df['Previously_Insured'].unique()

array([0, 1], dtype=int64)

In [10]:
#converting categorical date into numerical data

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
label_encoder = LabelEncoder()

In [13]:
df["Vehicle_Damage"] = label_encoder.fit_transform(df["Vehicle_Damage"]) 

In [14]:
df["Gender"] = label_encoder.fit_transform(df["Gender"]) 

In [15]:
df['Vehicle_Age'] = label_encoder.fit_transform(df['Vehicle_Age']) 

In [16]:
"""df['Gender'].replace(df['Gender'].value_counts().index, [0, 1], inplace=True)""" # anotherway

"df['Gender'].replace(df['Gender'].value_counts().index, [0, 1], inplace=True)"

In [17]:
df.drop(["id"],axis = 1,inplace =True)

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
scaler = MinMaxScaler(feature_range=(0,1))

In [33]:
df["Age"] = scaler.fit_transform(np.array(df["Age"]).reshape(-1,1))

In [37]:
df["Region_Code"] = scaler.fit_transform(np.array(df["Region_Code"]).reshape(-1,1))

In [39]:
df["Annual_Premium"] = scaler.fit_transform(np.array(df["Annual_Premium"]).reshape(-1,1))

In [40]:
df["Policy_Sales_Channel"] = scaler.fit_transform(np.array(df["Policy_Sales_Channel"]).reshape(-1,1))

In [41]:
df["Vintage"] = scaler.fit_transform(np.array(df["Vintage"]).reshape(-1,1))

In [45]:
x = df[['Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage']]

In [46]:
y = df["Response"]

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_validate,y_train,y_validate = train_test_split(x,y,test_size = 0.20)

In [49]:
from sklearn.svm import SVC

In [51]:
model = SVC()

In [52]:
model.fit(x_train,y_train)

SVC()

In [53]:
from sklearn.model_selection import cross_val_score

In [55]:
print(cross_val_score(model, x_validate, y_validate, cv=5))

[0.87709085 0.87709085 0.87709085 0.87708077 0.87708077]


In [57]:
print(np.mean(cross_val_score(model, x_validate, y_validate, cv=5)))

0.8770868179983866


In [73]:
test_df = pd.read_csv("TEST.csv")

In [59]:
test_df.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  291378    Male   31                1           18                   0   
1  154746  Female   24                1           15                   1   
2  218512  Female   25                1           14                   1   
3  173930    Male   49                1           28                   0   
4  241471    Male   55                1           45                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    1-2 Year            Yes            2630                   156      152  
1    < 1 Year             No           28105                   152      267  
2    < 1 Year             No           29302                   152      139  
3    1-2 Year            Yes           28357                    26       12  
4    1-2 Year            Yes           33288                    26       44

In [60]:
# categorical data to numerical data 

In [61]:
test_df["Vehicle_Damage"] = label_encoder.fit_transform(test_df["Vehicle_Damage"]) 

In [62]:
test_df["Gender"] = label_encoder.fit_transform(test_df["Gender"]) 

In [63]:
test_df['Vehicle_Age'] = label_encoder.fit_transform(test_df['Vehicle_Age']) 

In [64]:
#normilizing values

In [65]:
test_df["Age"] = scaler.fit_transform(np.array(test_df["Age"]).reshape(-1,1))

In [66]:
test_df["Region_Code"] = scaler.fit_transform(np.array(test_df["Region_Code"]).reshape(-1,1))

In [67]:
test_df["Annual_Premium"] = scaler.fit_transform(np.array(test_df["Annual_Premium"]).reshape(-1,1))

In [68]:
test_df["Policy_Sales_Channel"] = scaler.fit_transform(np.array(test_df["Policy_Sales_Channel"]).reshape(-1,1))

In [69]:
test_df["Vintage"] = scaler.fit_transform(np.array(test_df["Vintage"]).reshape(-1,1))

In [70]:
test_df.drop(["id"],axis = 1,inplace =True)

In [71]:
predictions = model.predict(test_df)

In [72]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
submission = {
    "id": test_df["id"],
    "Response":predictions
}

In [77]:
submission

{'id': 0        291378
 1        154746
 2        218512
 3        173930
 4        241471
           ...  
 76217    311352
 76218     35090
 76219     52767
 76220    298399
 76221    364035
 Name: id, Length: 76222, dtype: int64,
 'Response': array([0, 0, 0, ..., 0, 0, 0], dtype=int64)}

In [78]:
pd.DataFrame(submission).to_csv("submission.csv",index = False)